### ISSUE TITLE
tiqr u2f support ?

### ISSUE THREAD

**Issue by mcarbonneaux** [OpenConext/Stepup-tiqr#76]
there a plan to support u2f/webauthn of browser with tiqr ?

**Comment by joostd** [comment]
We are considering moving to an ECC-based authentication protocol, similar to and possibly compatible with U2F/WebAuthn.

However, using a mobile app like tiqr to profit from the WebAuthn API requires transport using USB (impractical), NFC (not available on iOS), or BLE (tricky to secure, and not yet available on browsers).

Take a look at [Krypton](https://krypt.co) for an interesting open source alternative that uses U2F under the hood with a browser plugin to use bluetooth in Chrome or Firefox.

**Comment by phavekes** [comment]
A webauthn-gssp is available now : See [Stepup-webauthn](https://github.com/OpenConext/Stepup-webauthn)

**Comment by mcarbonneaux** [comment]
> However, using a mobile app like tiqr to profit from the WebAuthn API requires transport using USB (impractical), NFC (not available on iOS), or BLE (tricky to secure, and not yet available on browsers).
> 

no they exist softtoken that emulate usb for webauthn, in the same you can interface tiqr with the browser... but you need to developpe usb driver to do that...
